### ISSUE TITLE
Application crashes when receiving wrong arguments in a REST call

### ISSUE THREAD

**Issue by carlos-technogi** [strongloop/strong-remoting#144]
With some arguments in a REST call the application crashes. For example:
http://0.0.0.0:3000/api/MyModel?filter=e
I get this:
/Users/carlos_technogi/development/projects/technogi/pip/api/node_modules/loopback/node_modules/strong-remoting/lib/shared-method.js:211
          throw err;
                ^
SyntaxError: Unexpected token e
    at Object.parse (native)
    at convertValueToTargetType (/Users/carlos_technogi/development/projects/technogi/pip/api/node_modules/loopback/node_modules/strong-remoting/lib/shared-method.js:275:19)
    at SharedMethod.invoke (/Users/carlos_technogi/development/projects/technogi/pip/api/node_modules/loopback/node_modules/strong-remoting/lib/shared-method.js:206:20)
    at HttpContext.invoke (/Users/carlos_technogi/development/projects/technogi/pip/api/node_modules/loopback/node_modules/strong-remoting/lib/http-context.js:268:12)
    at /Users/carlos_technogi/development/projects/technogi/pip/api/node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:501:9
    at execStack (/Users/carlos_technogi/development/projects/technogi/pip/api/node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:354:7)
    at /Users/carlos_technogi/development/projects/technogi/pip/api/node_modules/loopback/lib/application.js:319:13
    at /Users/carlos_technogi/development/projects/technogi/pip/api/node_modules/loopback/lib/model.js:295:5
    at /Users/carlos_technogi/development/projects/technogi/pip/api/node_modules/loopback/common/models/acl.js:433:23
    at /Users/carlos_technogi/development/projects/technogi/pip/api/node_modules/loopback/node_modules/async/lib/async.js:254:17

I can fix this, but I'm not sure where.

**Comment by AliYar-Khan** [comment]
This is happening at following versions too

loopback@2.42.0
  ├─┬ loopback-connector-remote@1.3.3
  │ └── strong-remoting@2.36.1 deduped
  └── strong-remoting@2.36.1
  
  Even though my end point is not accepting the variable but it is giving me such error ... posted this on stackover flow as well https://stackoverflow.com/questions/70209935/value-must-be-a-number-loopback-strong-remoting
