### ISSUE TITLE
On try create a user on loopback with heroku

### ISSUE THREAD

**Issue by paulomcnally** [strongloop/strong-remoting#432]
```
017-10-25T16:20:51.457821+00:00 app[web.1]: /app/node_modules/strong-remoting/lib/shared-method.js:157
2017-10-25T16:20:51.457843+00:00 app[web.1]:   if (/^prototype\./.test(name)) {
2017-10-25T16:20:51.457845+00:00 app[web.1]:                      ^
2017-10-25T16:20:51.457846+00:00 app[web.1]: 
2017-10-25T16:20:51.457846+00:00 app[web.1]: RangeError: Maximum call stack size exceeded
2017-10-25T16:20:51.457847+00:00 app[web.1]:     at RegExp.exec (native)
2017-10-25T16:20:51.457848+00:00 app[web.1]:     at RegExp.test (native)
2017-10-25T16:20:51.457849+00:00 app[web.1]:     at new SharedMethod (/app/node_modules/strong-remoting/lib/shared-method.js:157:22)
2017-10-25T16:20:51.457850+00:00 app[web.1]:     at SharedClass._define (/app/node_modules/strong-remoting/lib/shared-class.js:152:22)
2017-10-25T16:20:51.457850+00:00 app[web.1]:     at define (/app/node_modules/loopback/lib/model.js:270:9)
2017-10-25T16:20:51.457851+00:00 app[web.1]:     at Function.Model.hasManyRemoting (/app/node_modules/loopback/lib/model.js:625:5)
2017-10-25T16:20:51.457852+00:00 app[web.1]:     at resolver (/app/node_modules/loopback/lib/model.js:287:21)
2017-10-25T16:20:51.457852+00:00 app[web.1]:     at /app/node_modules/strong-remoting/lib/shared-class.js:114:14
2017-10-25T16:20:51.457853+00:00 app[web.1]:     at Array.forEach (native)
2017-10-25T16:20:51.457853+00:00 app[web.1]:     at SharedClass.methods (/app/node_modules/strong-remoting/lib/shared-class.js:113:19)
2017-10-25T16:20:51.457854+00:00 app[web.1]:     at new RestClass (/app/node_modules/strong-remoting/lib/rest-adapter.js:595:30)
2017-10-25T16:20:51.457854+00:00 app[web.1]:     at remotes.classes.map.c (/app/node_modules/strong-remoting/lib/rest-adapter.js:581:12)
2017-10-25T16:20:51.457855+00:00 app[web.1]:     at Array.map (native)
2017-10-25T16:20:51.457855+00:00 app[web.1]:     at RestAdapter.getClasses (/app/node_modules/strong-remoting/lib/rest-adapter.js:580:45)
2017-10-25T16:20:51.457855+00:00 app[web.1]:     at RestAdapter.createHandler (/app/node_modules/strong-remoting/lib/rest-adapter.js:293:22)
2017-10-25T16:20:51.457856+00:00 app[web.1]:     at RemoteObjects.handler (/app/node_modules/strong-remoting/lib/remote-objects.js:100:25)
2017-10-25T16:20:51.474698+00:00 app[web.1]: 
2017-10-25T16:20:51.483254+00:00 app[web.1]: npm ERR! Linux 3.13.0-133-generic
2017-10-25T16:20:51.483538+00:00 app[web.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2017-10-25T16:20:51.483756+00:00 app[web.1]: npm ERR! node v6.11.5
2017-10-25T16:20:51.483953+00:00 app[web.1]: npm ERR! npm  v3.10.10
2017-10-25T16:20:51.484147+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2017-10-25T16:20:51.484344+00:00 app[web.1]: npm ERR! api-uca@1.0.0 start: `node .`
2017-10-25T16:20:51.484460+00:00 app[web.1]: npm ERR! Exit status 1
2017-10-25T16:20:51.484607+00:00 app[web.1]: npm ERR! 
2017-10-25T16:20:51.484857+00:00 app[web.1]: npm ERR! Failed at the api-uca@1.0.0 start script 'node .'.
2017-10-25T16:20:51.484991+00:00 app[web.1]: npm ERR! Make sure you have the latest version of node.js and npm installed.
2017-10-25T16:20:51.485121+00:00 app[web.1]: npm ERR! If you do, this is most likely a problem with the api-uca package,
2017-10-25T16:20:51.485396+00:00 app[web.1]: npm ERR! Tell the author that this fails on your system:
2017-10-25T16:20:51.485253+00:00 app[web.1]: npm ERR! not with npm itself.
2017-10-25T16:20:51.485526+00:00 app[web.1]: npm ERR!     node .
2017-10-25T16:20:51.485673+00:00 app[web.1]: npm ERR! You can get information on how to open an issue for this project with:
2017-10-25T16:20:51.485806+00:00 app[web.1]: npm ERR!     npm bugs api-uca
2017-10-25T16:20:51.485931+00:00 app[web.1]: npm ERR! Or if that isn't available, you can get their info via:
2017-10-25T16:20:51.486062+00:00 app[web.1]: npm ERR!     npm owner ls api-uca
2017-10-25T16:20:51.486190+00:00 app[web.1]: npm ERR! There is likely additional logging output above.
2017-10-25T16:20:51.493934+00:00 app[web.1]: 
2017-10-25T16:20:51.494171+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2017-10-25T16:20:51.494246+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2017-10-25T16:20:51.578846+00:00 heroku[web.1]: Process exited with status 1
```

**Comment by bajtos** [comment]
@paulomcnally thank you for reporting the issue. How can we reproduce it? Could you please create a small app per our Bug reporting instructions described [here](https://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report)?
