### ISSUE TITLE
slc run crashed with error (Error: Cannot find module './lib/remote-objects')

### ISSUE THREAD

**Issue by kktam** [strongloop/strong-remoting#74]
Hi 

I am trying to compile strongloop sample app, and when I run "slc run" I get the following error.

$ slc run
strong-agent v0.4.6 profiling app 'sls-sample-app' pid '1096'
strong-agent dashboard is at https://strongops.strongloop.com
strong-agent using collector https://collector.strongloop.com:443
supervisor running without clustering (unsupervised)

module.js:340
    throw err;
          ^
Error: Cannot find module './lib/remote-objects'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at Module.module.__proto__.require (/usr/local/lib/node_modules/strong-supervisor/node_modules/strong-agent/lib/agent.js:170:40)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/nelsontam/Documents/Work/nodejs/sls-sample-app/node_modules/loopback/node_modules/strong-remoting/index.js:5:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

I am running OSX Maverick 10.8 and can anyone tell me how to install the missing remote-objects  module?

**Comment by VinodhThiagarajan86** [comment]
Worked for me too !
